#pragma once

// To add characters or palette lists:
// * If you need a new character, add them to DBZHD_SNES_UNITS.
// * Add an associated collection of their respective nodes
// * or expand nodes as needed
// * Then create the set of palettes for that character
// That should be it.  Good luck.

const sGame_PaletteDataset DBZHD_SNES_GOKU_PALETTES_P1[] =
{
    { L"Goku P1 (Day)", 0xB0000, 0xB0020 },
};

const sGame_PaletteDataset DBZHD_SNES_GOKU_PALETTES_P2[] =
{
    { L"Goku P2 (Day)", 0xB0020, 0xB0040 },
};

const sGame_PaletteDataset DBZHD_SNES_VEGETA_PALETTES_P1[] =
{
    { L"Vegeta P1 (Day)", 0xB0200, 0xB0220 },
};

const sGame_PaletteDataset DBZHD_SNES_VEGETA_PALETTES_P2[] =
{
    { L"Vegeta P2 (Day)", 0xB0220, 0xB0240 },
};

const sGame_PaletteDataset DBZHD_SNES_GOTENKS_PALETTES_P1[] =
{
    { L"Gotenks P1 (Day)", 0xB0A80, 0xB0AA0 },
};

const sGame_PaletteDataset DBZHD_SNES_GOTENKS_PALETTES_P2[] =
{
    { L"Gotenks P2 (Day)", 0xB0AA0, 0xB0AC0 },
};

const sGame_PaletteDataset DBZHD_SNES_GOHAN_PALETTES_P1[] =
{
    { L"Gohan P1 (Day)", 0xB0500, 0xB0520 },
};

const sGame_PaletteDataset DBZHD_SNES_GOHAN_PALETTES_P2[] =
{
    { L"Gohan P2 (Day)", 0xB0520, 0xB0540 },
};

const sGame_PaletteDataset DBZHD_SNES_VEGITO_PALETTES_P1[] =
{
    { L"Vegito P1 (Day)", 0xB0EB0, 0xB0ED0 },
};

const sGame_PaletteDataset DBZHD_SNES_VEGITO_PALETTES_P2[] =
{
    { L"Vegito P2 (Day)", 0xB0ED0, 0xB0EF0 },
};

const sGame_PaletteDataset DBZHD_SNES_PICCOLO_PALETTES_P1[] =
{
    { L"Piccolo P1 (Day)", 0xB10F0, 0xB1110 },
};

const sGame_PaletteDataset DBZHD_SNES_PICCOLO_PALETTES_P2[] =
{
    { L"Piccolo P2 (Day)", 0xB1110, 0xB1130 },
};

const sGame_PaletteDataset DBZHD_SNES_BUU_PALETTES_P1[] =
{
    { L"Buu P1 (Day)", 0xB1A70, 0xB1A90 },
};

const sGame_PaletteDataset DBZHD_SNES_BUU_PALETTES_P2[] =
{
    { L"Buu P2 (Day)", 0xB1A90, 0xB1AB0 },
};

const sGame_PaletteDataset DBZHD_SNES_KIDBUU_PALETTES_P1[] =
{
    { L"Kid Buu P1 (Day)", 0xB1870, 0xB1890 },
};

const sGame_PaletteDataset DBZHD_SNES_KIDBUU_PALETTES_P2[] =
{
    { L"Kid Buu P2 (Day)", 0xB1890, 0xB18B0 },
};

const sGame_PaletteDataset DBZHD_SNES_FRIEZA_PALETTES_P1[] =
{
    { L"Frieza P1 (Day)", 0xB07C0, 0xB07E0 },
};

const sGame_PaletteDataset DBZHD_SNES_FRIEZA_PALETTES_P2[] =
{
    { L"Frieza P2 (Day)", 0xB07E0, 0xB0800 },
};

const sGame_PaletteDataset DBZHD_SNES_CELL_PALETTES_P1[] =
{
    { L"Cell P1 (Day)", 0xB13F0, 0xB1410 },
};

const sGame_PaletteDataset DBZHD_SNES_CELL_PALETTES_P2[] =
{
    { L"Cell P2 (Day)", 0xB1410, 0xB1430 },
};

const sGame_PaletteDataset DBZHD_SNES_CELL_PALETTES_SHARED[] =
{
    { L"Intro", 0xB16F0, 0xB1710 },
};    

const sDescTreeNode DBZHD_SNES_GOKU_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOKU_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_GOKU_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOKU_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_GOKU_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_VEGETA_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGETA_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_VEGETA_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGETA_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_VEGETA_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_GOTENKS_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOTENKS_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_GOTENKS_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOTENKS_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_GOTENKS_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_GOHAN_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOHAN_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_GOHAN_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOHAN_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_GOHAN_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_VEGITO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGITO_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_VEGITO_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGITO_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_VEGITO_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_PICCOLO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_PICCOLO_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_PICCOLO_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_PICCOLO_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_PICCOLO_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_BUU_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_BUU_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_BUU_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_BUU_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_BUU_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_KIDBUU_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_KIDBUU_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_KIDBUU_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_KIDBUU_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_KIDBUU_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_FRIEZA_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_FRIEZA_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_FRIEZA_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_FRIEZA_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_FRIEZA_PALETTES_P2) },
};

const sDescTreeNode DBZHD_SNES_CELL_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_CELL_PALETTES_P1, ARRAYSIZE(DBZHD_SNES_CELL_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_CELL_PALETTES_P2, ARRAYSIZE(DBZHD_SNES_CELL_PALETTES_P2) },
    { L"Shared", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_CELL_PALETTES_SHARED, ARRAYSIZE(DBZHD_SNES_CELL_PALETTES_SHARED) },
};

const sDescTreeNode DBZHD_SNES_UNITS[] =
{
    { L"Goku", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOKU_COLLECTION, ARRAYSIZE(DBZHD_SNES_GOKU_COLLECTION) },
    { L"Vegeta", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGETA_COLLECTION, ARRAYSIZE(DBZHD_SNES_VEGETA_COLLECTION) },
    { L"Gotenks", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOTENKS_COLLECTION, ARRAYSIZE(DBZHD_SNES_GOTENKS_COLLECTION) },
    { L"Gohan", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_GOHAN_COLLECTION, ARRAYSIZE(DBZHD_SNES_GOHAN_COLLECTION) },
    { L"Vegito", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_VEGITO_COLLECTION, ARRAYSIZE(DBZHD_SNES_VEGITO_COLLECTION) },
    { L"Piccolo", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_PICCOLO_COLLECTION, ARRAYSIZE(DBZHD_SNES_PICCOLO_COLLECTION) },
    { L"Buu", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_BUU_COLLECTION, ARRAYSIZE(DBZHD_SNES_BUU_COLLECTION) },
    { L"Kid Buu", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_KIDBUU_COLLECTION, ARRAYSIZE(DBZHD_SNES_KIDBUU_COLLECTION) },
    { L"Frieza", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_FRIEZA_COLLECTION, ARRAYSIZE(DBZHD_SNES_FRIEZA_COLLECTION) },
    { L"Cell", DESC_NODETYPE_TREE, (void*)DBZHD_SNES_CELL_COLLECTION, ARRAYSIZE(DBZHD_SNES_CELL_COLLECTION) },
};

constexpr auto DBZHD_SNES_NUMUNIT = ARRAYSIZE(DBZHD_SNES_UNITS);

#define DBZHD_SNES_EXTRALOC DBZHD_SNES_NUMUNIT

// We extend this array with data groveled from the extensible extras file, if any.
const stExtraDef DBZHD_SNES_EXTRA[] =
{
    // Start
    { UNIT_START_VALUE },

    { INVALID_UNIT_VALUE }
};
