#pragma once

// To add characters or palette lists:
// * If you need a new character, add them to JCHAN_A_UNITS.
// * Add an associated collection of their respective nodes
// * or expand nodes as needed
// * Then create the set of palettes for that character
// That should be it.  Good luck.

const std::vector<uint16_t> JCHAN_A_IMGIDS_USED =
{
};

const sGame_PaletteDataset JCHAN_A_THORSTEN_PALETTES_LPHP[] =
{
    { L"Thorsten", 0xc0000, 0xc0200 },
};

const sGame_PaletteDataset JCHAN_A_THORSTEN_PALETTES_LKHK[] =
{
    { L"Thorsten", 0xc0200, 0xc0400 },
};

const sGame_PaletteDataset JCHAN_A_THORSTEN_PALETTES_BOSS1[] =
{
    { L"Demon Thorsten", 0xc0400, 0xc0600 },
};

const sGame_PaletteDataset JCHAN_A_THORSTEN_PALETTES_BOSS2[] =
{
    { L"Demon Thorsten", 0xc0600, 0xc0800 },
};

const sGame_PaletteDataset JCHAN_A_SAM_PALETTES_LPHP[] =
{
    { L"Sam", 0xc0800, 0xc0a00 },
};

const sGame_PaletteDataset JCHAN_A_SAM_PALETTES_LKHK[] =
{
    { L"Sam", 0xc0a00, 0xc0c00 },
};

const sGame_PaletteDataset JCHAN_A_SAM_PALETTES_BOSS1[] =
{
    { L"Black Sam", 0xc0c00, 0xc0e00 },
};

const sGame_PaletteDataset JCHAN_A_SAM_PALETTES_BOSS2[] =
{
    { L"Black Sam", 0xc0e00, 0xc1000 },
};

const sGame_PaletteDataset JCHAN_A_SPIRITJCHAN_PALETTES_LPHP[] =
{
    { L"Spiritual Kung-Fu Jackie", 0xc1000, 0xc1200 },
};

const sGame_PaletteDataset JCHAN_A_SPIRITJCHAN_PALETTES_LKHK[] =
{
    { L"Spiritual Kung-Fu Jackie", 0xc1200, 0xc1400 },
};

const sGame_PaletteDataset JCHAN_A_SPIRITJCHAN_PALETTES_BOSS1[] =
{
    { L"Hyper Dragonball Jackie", 0xc1400, 0xc1600 },
};

const sGame_PaletteDataset JCHAN_A_SPIRITJCHAN_PALETTES_BOSS2[] =
{
    { L"Hyper Dragonball Jackie", 0xc1600, 0xc1800 },
};

const sGame_PaletteDataset JCHAN_A_DRUNKJCHAN_PALETTES_LPHP[] =
{
    { L"Drunken Master Jackie", 0xc1800, 0xc1a00 },
};

const sGame_PaletteDataset JCHAN_A_DRUNKJCHAN_PALETTES_LKHK[] =
{
    { L"Drunken Master Jackie", 0xc1a00, 0xc1c00 },
};

const sGame_PaletteDataset JCHAN_A_DRUNKJCHAN_PALETTES_BOSS1[] =
{
    { L"Hyper Drunken Jackie", 0xc1c00, 0xc1e00 },
};

const sGame_PaletteDataset JCHAN_A_DRUNKJCHAN_PALETTES_BOSS2[] =
{
    { L"Hyper Drunken Jackie", 0xc1e00, 0xc2000 },
};

const sGame_PaletteDataset JCHAN_A_YEUNG_PALETTES_LPHP[] =
{
    { L"Yeung", 0xc2000, 0xc2200 },
};

const sGame_PaletteDataset JCHAN_A_YEUNG_PALETTES_LKHK[] =
{
    { L"Yeung", 0xc2200, 0xc2400 },
};

const sGame_PaletteDataset JCHAN_A_YEUNG_PALETTES_BOSS1[] =
{
    { L"Shadow Yeung", 0xc2400, 0xc2600 },
};

const sGame_PaletteDataset JCHAN_A_YEUNG_PALETTES_BOSS2[] =
{
    { L"Shadow Yeung", 0xc2600, 0xc2800 },
};

const sGame_PaletteDataset JCHAN_A_ADMIRALJCHAN_PALETTES_LPHP[] =
{
    { L"Admiral Jackie", 0xc2800, 0xc2a00 },
};

const sGame_PaletteDataset JCHAN_A_ADMIRALJCHAN_PALETTES_LKHK[] =
{
    { L"Admiral Jackie", 0xc2a00, 0xc2c00 },
};

const sGame_PaletteDataset JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS1[] =
{
    { L"Hyper Admiral Jackie", 0xc2c00, 0xc2e00 },
};

const sGame_PaletteDataset JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS2[] =
{
    { L"Hyper Admiral Jackie", 0xc2e00, 0xc3000 },
};

const sGame_PaletteDataset JCHAN_A_LION_PALETTES_LPHP[] =
{
    { L"Lion", 0xc3000, 0xc3200 },
};

const sGame_PaletteDataset JCHAN_A_LION_PALETTES_LKHK[] =
{
    { L"Lion", 0xc3200, 0xc3400 },
};

const sGame_PaletteDataset JCHAN_A_LION_PALETTES_BOSS1[] =
{
    { L"Evil Lion", 0xc3400, 0xc3600 },
};

const sGame_PaletteDataset JCHAN_A_LION_PALETTES_BOSS2[] =
{
    { L"Evil Lion", 0xc3600, 0xc3800 },
};

const sGame_PaletteDataset JCHAN_A_KIMMAREE_PALETTES_LPHP[] =
{
    { L"Kim-Maree", 0xc3800, 0xc3a00 },
};

const sGame_PaletteDataset JCHAN_A_KIMMAREE_PALETTES_LKHK[] =
{
    { L"Kim-Maree", 0xc3a00, 0xc3c00 },
};

const sGame_PaletteDataset JCHAN_A_KIMMAREE_PALETTES_BOSS1[] =
{
    { L"Dirty Maree", 0xc3c00, 0xc3e00 },
};

const sGame_PaletteDataset JCHAN_A_KIMMAREE_PALETTES_BOSS2[] =
{
    { L"Palette", 0xc3e00, 0xc4000 },
};

const sGame_PaletteDataset JCHAN_A_LAU_PALETTES_LPHP[] =
{
    { L"Lau", 0xc4000, 0xc4200 },
};

const sGame_PaletteDataset JCHAN_A_LAU_PALETTES_LKHK[] =
{
    { L"Lau", 0xc4200, 0xc4400 },
};

const sGame_PaletteDataset JCHAN_A_LAU_PALETTES_BOSS1[] =
{
    { L"Dark Lau", 0xc4400, 0xc4600 },
};

const sGame_PaletteDataset JCHAN_A_LAU_PALETTES_BOSS2[] =
{
    { L"Dark Lau", 0xc4600, 0xc4800 },
};

const sGame_PaletteDataset JCHAN_A_BONUS_PALETTES_BONUS[] =
{
    { L"\"PLAYER SELECT\" text", 0xE0060, 0xE0080 },
    { L"Character Names", 0xE0080, 0xE00C0 },
    { L"Hitsparks", 0xE1D20, 0xE1DE0 },
    { L"Fire Finish BG", 0xE3200, 0xE3400 },
    { L"Purple Fire Fight Start BG", 0xE3400, 0xE3600 },
    { L"Hit Combo Numbers", 0xE0120, 0xE01E0 },
    { L"KANEKO Logo", 0xE0A40, 0xE0A60 },
    { L"Icons next to \"PLAYER SELECT\" text", 0xE0A80, 0xE0AA0 },
    { L"Win Icon", 0xE0C80, 0xE0CA0 },
};

const sDescTreeNode JCHAN_A_LAU_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_LAU_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_LAU_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_LAU_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_LAU_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_LAU_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_LAU_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_LAU_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_LAU_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_YEUNG_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_YEUNG_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_YEUNG_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_YEUNG_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_YEUNG_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_YEUNG_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_YEUNG_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_YEUNG_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_YEUNG_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_THORSTEN_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_THORSTEN_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_THORSTEN_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_THORSTEN_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_THORSTEN_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_THORSTEN_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_THORSTEN_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_THORSTEN_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_THORSTEN_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_DRUNKJCHAN_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_DRUNKJCHAN_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_DRUNKJCHAN_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_DRUNKJCHAN_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_DRUNKJCHAN_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_DRUNKJCHAN_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_DRUNKJCHAN_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_DRUNKJCHAN_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_DRUNKJCHAN_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_SPIRITJCHAN_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_SPIRITJCHAN_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_SPIRITJCHAN_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_SPIRITJCHAN_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_SPIRITJCHAN_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_SPIRITJCHAN_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_SPIRITJCHAN_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_SPIRITJCHAN_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_SPIRITJCHAN_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_ADMIRALJCHAN_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_ADMIRALJCHAN_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_ADMIRALJCHAN_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_ADMIRALJCHAN_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_ADMIRALJCHAN_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_ADMIRALJCHAN_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_SAM_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_SAM_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_SAM_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_SAM_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_SAM_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_SAM_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_SAM_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_SAM_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_SAM_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_KIMMAREE_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_KIMMAREE_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_KIMMAREE_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_KIMMAREE_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_KIMMAREE_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_KIMMAREE_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_KIMMAREE_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_KIMMAREE_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_KIMMAREE_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_LION_COLLECTION[] =
{
    { L"LP/HP", DESC_NODETYPE_TREE, (void*)JCHAN_A_LION_PALETTES_LPHP, ARRAYSIZE(JCHAN_A_LION_PALETTES_LPHP) },
    { L"LK/HK", DESC_NODETYPE_TREE, (void*)JCHAN_A_LION_PALETTES_LKHK, ARRAYSIZE(JCHAN_A_LION_PALETTES_LKHK) },
    { L"P1 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_LION_PALETTES_BOSS1, ARRAYSIZE(JCHAN_A_LION_PALETTES_BOSS1) },
    { L"P2 (Boss)", DESC_NODETYPE_TREE, (void*)JCHAN_A_LION_PALETTES_BOSS2, ARRAYSIZE(JCHAN_A_LION_PALETTES_BOSS2) },
};

const sDescTreeNode JCHAN_A_BONUS_COLLECTION[] =
{
    { L"Bonus", DESC_NODETYPE_TREE, (void*)JCHAN_A_BONUS_PALETTES_BONUS, ARRAYSIZE(JCHAN_A_BONUS_PALETTES_BONUS) },
};

const sDescTreeNode JCHAN_A_UNITS[] =
{
    { L"Lau", DESC_NODETYPE_TREE, (void*)JCHAN_A_LAU_COLLECTION, ARRAYSIZE(JCHAN_A_LAU_COLLECTION) },
    { L"Yeung", DESC_NODETYPE_TREE, (void*)JCHAN_A_YEUNG_COLLECTION, ARRAYSIZE(JCHAN_A_YEUNG_COLLECTION) },
    { L"Thorsten", DESC_NODETYPE_TREE, (void*)JCHAN_A_THORSTEN_COLLECTION, ARRAYSIZE(JCHAN_A_THORSTEN_COLLECTION) },
    { L"Drunken Fist Jackie Chan", DESC_NODETYPE_TREE, (void*)JCHAN_A_DRUNKJCHAN_COLLECTION, ARRAYSIZE(JCHAN_A_DRUNKJCHAN_COLLECTION) },
    { L"Spiritual Kung-Fu Jackie Chan", DESC_NODETYPE_TREE, (void*)JCHAN_A_SPIRITJCHAN_COLLECTION, ARRAYSIZE(JCHAN_A_SPIRITJCHAN_COLLECTION) },
    { L"Admiral Jackie", DESC_NODETYPE_TREE, (void*)JCHAN_A_ADMIRALJCHAN_COLLECTION, ARRAYSIZE(JCHAN_A_ADMIRALJCHAN_COLLECTION) },
    { L"Sam", DESC_NODETYPE_TREE, (void*)JCHAN_A_SAM_COLLECTION, ARRAYSIZE(JCHAN_A_SAM_COLLECTION) },
    { L"Kim-Maree", DESC_NODETYPE_TREE, (void*)JCHAN_A_KIMMAREE_COLLECTION, ARRAYSIZE(JCHAN_A_KIMMAREE_COLLECTION) },
    { L"Mysterious Lion", DESC_NODETYPE_TREE, (void*)JCHAN_A_LION_COLLECTION, ARRAYSIZE(JCHAN_A_LION_COLLECTION) },
    { L"Bonus Palettes", DESC_NODETYPE_TREE, (void*)JCHAN_A_BONUS_COLLECTION, ARRAYSIZE(JCHAN_A_BONUS_COLLECTION) },
};
