#pragma once

// To add characters or palette lists:
// * If you need a new character, add them to MK1_SNES_UNITS.
// * Add an associated collection of their respective nodes
// * or expand nodes as needed
// * Then create the set of palettes for that character
// That should be it.  Good luck.

const std::vector<UINT16> MK1_SNES_IMGIDS_USED =
{
    // stub
    indexJoJoRPGSprites_Enemies,         // 0xA6
};

const sGame_PaletteDataset MK1_SNES_LIUKANG_P1_PALETTES[] =
{
    { L"Liu Kang P1", 0x1CFD06, 0x1CFD26 },
};

const sGame_PaletteDataset MK1_SNES_LIUKANG_P2_PALETTES[] =
{
    { L"Liu Kang P2", 0x1CFD66, 0x1CFD86 },
};

const sGame_PaletteDataset MK1_SNES_LIUKANG_EFFECT_PALETTES[] =
{
    { L"Liu Kang's Fireball", 0x1CFD26, 0x1CFD46 },
};

const sGame_PaletteDataset MK1_SNES_JONNYCAGE_P1_PALETTES[] =
{
    { L"Johnny Cage P1", 0x1CFB86, 0x1CFBA6 },
};

const sGame_PaletteDataset MK1_SNES_JONNYCAGE_P2_PALETTES[] =
{
    { L"Johnny Cage P2", 0x1CFBE6, 0x1CFC06 },
};

const sGame_PaletteDataset MK1_SNES_JONNYCAGE_EFFECT_PALETTES[] =
{
    { L"Cage's Green Forceball", 0x1CFBA6, 0x1CFBC6 },
};

const sGame_PaletteDataset MK1_SNES_REPTILE_PALETTES[] =
{
    { L"Reptile", 0x1CFFC6, 0x1CFFE6 },
};

const sGame_PaletteDataset MK1_SNES_SUBZERO_P1_PALETTES[] =
{
    { L"Sub-Zero P1", 0x1CFE06, 0x1CFE26 },
};

const sGame_PaletteDataset MK1_SNES_SUBZERO_P2_PALETTES[] =
{
    { L"Sub-Zero P2", 0x1CFE66, 0x1CFE86 },
};

const sGame_PaletteDataset MK1_SNES_SUBZERO_EFFECT_PALETTES[] =
{
    { L"Sub-Zero's Ice", 0x1CFE26, 0x1CFE46 },
};

const sGame_PaletteDataset MK1_SNES_SCORPION_P1_PALETTES[] =
{
    { L"Scorpion P1", 0x1CFD86, 0x1CFDA6 },
};

const sGame_PaletteDataset MK1_SNES_SCORPION_P2_PALETTES[] =
{
    { L"Scorpion P2", 0x1CFDE6, 0x1CFE06 },
};

const sGame_PaletteDataset MK1_SNES_SCORPION_EFFECT_PALETTES[] =
{
    { L"Skeleton (Scorpion Fatality)", 0x5BE9, 0x5C09 },
};

const sGame_PaletteDataset MK1_SNES_RAYDEN_P1_PALETTES[] =
{
    { L"Rayden P1", 0x1CFC86, 0x1CFCA6 },
};

const sGame_PaletteDataset MK1_SNES_RAYDEN_P2_PALETTES[] =
{
    { L"Rayden P2", 0x1CFCE6, 0x1CFD06 },
};

const sGame_PaletteDataset MK1_SNES_RAYDEN_EFFECT_PALETTES[] =
{
    { L"Rayden's Lightning/Ext", 0x1CFCA6, 0x1CFCC6 },
};

const sGame_PaletteDataset MK1_SNES_KANO_P1_PALETTES[] =
{
    { L"Kano P1", 0x1CFC06, 0x1CFC26 },
};

const sGame_PaletteDataset MK1_SNES_KANO_P2_PALETTES[] =
{
    { L"Kano P2", 0x1CFC66, 0x1CFC86 },
};

const sGame_PaletteDataset MK1_SNES_KANO_EFFECT_PALETTES[] =
{
    { L"Kano's Blue Knives", 0x1CFC26, 0x1CFC46 },
};

const sGame_PaletteDataset MK1_SNES_SONYA_P1_PALETTES[] =
{
    { L"Sonya P1", 0x1CFE86, 0x1CFEA6 },
};

const sGame_PaletteDataset MK1_SNES_SONYA_P2_PALETTES[] =
{
    { L"Sonya P2", 0x1CFEE6, 0x1CFF06 },
};

const sGame_PaletteDataset MK1_SNES_SONYA_EFFECT_PALETTES[] =
{
    { L"Sonya's Beam/Fire", 0x1CFEA6, 0x1CFEC6 },
};

const sGame_PaletteDataset MK1_SNES_GORO_PALETTES[] =
{
    { L"Goro", 0x1CFF06, 0x1CFF26 },
    { L"Goro's Fireball", 0x1CFF26, 0x1CFF46 },
};

const sGame_PaletteDataset MK1_SNES_SHANGTSUNG_PALETTES[] =
{
    { L"Shang Tsung", 0x1CFF86, 0x1CFFA6 },
};

const sGame_PaletteDataset MK1_SNES_BONUS_PALETTES[] =
{
    { L"Sweat/Blood", 0x1C16, 0x1C36 },
};

const sDescTreeNode MK1_SNES_LIUKANG_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_LIUKANG_P1_PALETTES, ARRAYSIZE(MK1_SNES_LIUKANG_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_LIUKANG_P2_PALETTES, ARRAYSIZE(MK1_SNES_LIUKANG_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_LIUKANG_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_LIUKANG_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_JONNYCAGE_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_JONNYCAGE_P1_PALETTES, ARRAYSIZE(MK1_SNES_JONNYCAGE_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_JONNYCAGE_P2_PALETTES, ARRAYSIZE(MK1_SNES_JONNYCAGE_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_JONNYCAGE_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_JONNYCAGE_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_REPTILE_COLLECTION[] =
{
    { L"Palettes", DESC_NODETYPE_TREE, (void*)MK1_SNES_REPTILE_PALETTES, ARRAYSIZE(MK1_SNES_REPTILE_PALETTES) },
};

const sDescTreeNode MK1_SNES_SUBZERO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_SUBZERO_P1_PALETTES, ARRAYSIZE(MK1_SNES_SUBZERO_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_SUBZERO_P2_PALETTES, ARRAYSIZE(MK1_SNES_SUBZERO_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_SUBZERO_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_SUBZERO_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_SCORPION_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_SCORPION_P1_PALETTES, ARRAYSIZE(MK1_SNES_SCORPION_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_SCORPION_P2_PALETTES, ARRAYSIZE(MK1_SNES_SCORPION_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_SCORPION_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_SCORPION_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_KANO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_KANO_P1_PALETTES, ARRAYSIZE(MK1_SNES_KANO_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_KANO_P2_PALETTES, ARRAYSIZE(MK1_SNES_KANO_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_KANO_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_KANO_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_SONYA_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_SONYA_P1_PALETTES, ARRAYSIZE(MK1_SNES_SONYA_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_SONYA_P2_PALETTES, ARRAYSIZE(MK1_SNES_SONYA_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_SONYA_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_SONYA_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_RAYDEN_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)MK1_SNES_RAYDEN_P1_PALETTES, ARRAYSIZE(MK1_SNES_RAYDEN_P1_PALETTES) },
    { L"P2", DESC_NODETYPE_TREE, (void*)MK1_SNES_RAYDEN_P2_PALETTES, ARRAYSIZE(MK1_SNES_RAYDEN_P2_PALETTES) },
    { L"Effects", DESC_NODETYPE_TREE, (void*)MK1_SNES_RAYDEN_EFFECT_PALETTES, ARRAYSIZE(MK1_SNES_RAYDEN_EFFECT_PALETTES) },
};

const sDescTreeNode MK1_SNES_GORO_COLLECTION[] =
{
    { L"Palettes", DESC_NODETYPE_TREE, (void*)MK1_SNES_GORO_PALETTES, ARRAYSIZE(MK1_SNES_GORO_PALETTES) },
};

const sDescTreeNode MK1_SNES_SHANGTSUNG_COLLECTION[] =
{
    { L"Palettes", DESC_NODETYPE_TREE, (void*)MK1_SNES_SHANGTSUNG_PALETTES, ARRAYSIZE(MK1_SNES_SHANGTSUNG_PALETTES) },
};

const sDescTreeNode MK1_SNES_BONUS_COLLECTION[] =
{
    { L"Palettes", DESC_NODETYPE_TREE, (void*)MK1_SNES_BONUS_PALETTES, ARRAYSIZE(MK1_SNES_BONUS_PALETTES) },
};

const sDescTreeNode MK1_SNES_UNITS[] =
{
    { L"Liu Kang", DESC_NODETYPE_TREE, (void*)MK1_SNES_LIUKANG_COLLECTION, ARRAYSIZE(MK1_SNES_LIUKANG_COLLECTION) },
    { L"Kano", DESC_NODETYPE_TREE, (void*)MK1_SNES_KANO_COLLECTION, ARRAYSIZE(MK1_SNES_KANO_COLLECTION) },
    { L"Jonny Cage", DESC_NODETYPE_TREE, (void*)MK1_SNES_JONNYCAGE_COLLECTION, ARRAYSIZE(MK1_SNES_JONNYCAGE_COLLECTION) },
    { L"Reptile", DESC_NODETYPE_TREE, (void*)MK1_SNES_REPTILE_COLLECTION, ARRAYSIZE(MK1_SNES_REPTILE_COLLECTION) },
    { L"Sub-Zero", DESC_NODETYPE_TREE, (void*)MK1_SNES_SUBZERO_COLLECTION, ARRAYSIZE(MK1_SNES_SUBZERO_COLLECTION) },
    { L"Scorpion", DESC_NODETYPE_TREE, (void*)MK1_SNES_SCORPION_COLLECTION, ARRAYSIZE(MK1_SNES_SCORPION_COLLECTION) },
    { L"Sonya", DESC_NODETYPE_TREE, (void*)MK1_SNES_SONYA_COLLECTION, ARRAYSIZE(MK1_SNES_SONYA_COLLECTION) },
    { L"Rayden", DESC_NODETYPE_TREE, (void*)MK1_SNES_RAYDEN_COLLECTION, ARRAYSIZE(MK1_SNES_RAYDEN_COLLECTION) },
    { L"Goro", DESC_NODETYPE_TREE, (void*)MK1_SNES_GORO_COLLECTION, ARRAYSIZE(MK1_SNES_GORO_COLLECTION) },
    { L"Shang Tsung", DESC_NODETYPE_TREE, (void*)MK1_SNES_SHANGTSUNG_COLLECTION, ARRAYSIZE(MK1_SNES_SHANGTSUNG_COLLECTION) },
    { L"Bonus Palettes", DESC_NODETYPE_TREE, (void*)MK1_SNES_BONUS_COLLECTION, ARRAYSIZE(MK1_SNES_BONUS_COLLECTION) },
};

constexpr auto MK1_SNES_NUMUNIT = ARRAYSIZE(MK1_SNES_UNITS);

#define MK1_SNES_EXTRALOC MK1_SNES_NUMUNIT

// We extend this array with data groveled from the extensible extras file, if any.
const stExtraDef MK1_SNES_EXTRA[] =
{
    // Start
    { UNIT_START_VALUE },

    { INVALID_UNIT_VALUE }
};
