#pragma once

#include "P4AU_Common.h"

const std::vector<sGCBUPF_BasicFileData> PersonaCharacterData_NESICA =
{
    //Alphabetical
    { L"char\\char_ag_pal.pac",    L"Aigis",                          278560,    PersonaNodes_Normal, Persona4PalettesAigis,      0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Aigis (CharaSelect)",            19154912,  PersonaNodes_CSel, Persona4PalettesAigisCSEL,  0x191a90 },
    { L"char\\char_ak_pal.pac",    L"Akihiko Sanada",                 278560,    PersonaNodes_Normal, Persona4PalettesAkihiko,    0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Akihiko Sanada (CharaSelect)",   19154912,  PersonaNodes_CSel, Persona4PalettesAkihikoCSEL,0x24BE20 },
    { L"char\\char_ce_pal.pac",    L"Chie Satonaka",                  278560,    PersonaNodes_Normal, Persona4PalettesChie,       0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Chie Satonaka (CharaSelect)",    19154912,  PersonaNodes_CSel, Persona4PalettesChieCSEL,   0x412340 },
    { L"char\\char_el_pal.pac",    L"Elizabeth",                      278560,    PersonaNodes_Normal, Persona4PalettesElizabeth,  0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Elizabeth (CharaSelect)",        19154912,  PersonaNodes_CSel, Persona4PalettesElizabethCSEL,0x5577D0 },
    { L"char\\char_ju_pal.pac",    L"Junpei Iori",                    278560,    PersonaNodes_Normal, Persona4PalettesJunpei,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Junpei Iori (CharaSelect)",      19154912,  PersonaNodes_CSel, Persona4PalettesJunpeiCSEL, 0x5FE500 },
    { L"char\\char_ka_pal.pac",    L"Kanji Tatsumi",                  278560,    PersonaNodes_Normal, Persona4PalettesKanji,      0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Kanji Tatsumi (CharaSelect)",    19154912,  PersonaNodes_CSel, Persona4PalettesKanjiCSEL,  0x746950 },
    { L"char\\char_am_pal.pac",    L"Ken Amada & Koromaru",           278560,    PersonaNodes_Normal, Persona4PalettesKen,        0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Ken Amada & Koromaru (CharaSelect)", 19154912, PersonaNodes_CSel, Persona4PalettesKenCSEL,  0x2E9CD0 },
    { L"char\\char_la_pal.pac",    L"Labrys",                         278560,    PersonaNodes_Normal, Persona4PalettesLabrys,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Labrys (CharaSelect)",           19154912,  PersonaNodes_CSel, Persona4PalettesLabrysCSEL, 0x90E2F0 },
    { L"char\\char_nx_pal.pac",    L"Margaret",                       278560,    PersonaNodes_Normal, Persona4PalettesMargaret,   0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Margaret (CharaSelect)",         19154912,  PersonaNodes_CSel, Persona4PalettesMargaretCSEL,0xF4E5A0 },
    { L"char\\char_mr_pal.pac",    L"Marie",                          278560,    PersonaNodes_Normal, Persona4PalettesMarie,      0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Marie (CharaSelect)",            19154912,  PersonaNodes_CSel, Persona4PalettesMarieCSEL,  0xC857B0 },
    { L"char\\char_mi_pal.pac",    L"Mitsuru Kirijo",                 278560,    PersonaNodes_Normal, Persona4PalettesMitsuru,    0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Mitsuru Kirijo (CharaSelect)",   19154912,  PersonaNodes_CSel, Persona4PalettesMitsuruCSEL,0xBA8150 },
    { L"char\\char_na_pal.pac",    L"Naoto Shirogane",                278560,    PersonaNodes_Normal, Persona4PalettesNaoto,      0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Naoto Shirogane (CharaSelect)",  19154912,  PersonaNodes_CSel, Persona4PalettesNaotoCSEL,  0xD17BD0 },
    { L"char\\char_ri_pal.pac",    L"Rise Kujikawa",                  278560,    PersonaNodes_Normal, Persona4PalettesRise,       0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Rise Kujikawa (CharaSelect)",    19154912,  PersonaNodes_CSel, Persona4PalettesRiseCSEL,   0x1026140 },
    { L"char\\char_ls_pal.pac",    L"Shadow Labrys",                  278560,    PersonaNodes_Normal, Persona4PalettesShadow,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Shadow Labrys (CharaSelect)",    19154912,  PersonaNodes_CSel, Persona4PalettesShadowCSEL, 0xAC5990 },
    { L"char\\char_no_pal.pac",    L"Sho (Solo)",                     278560,    PersonaNodes_Normal, Persona4PalettesSolo,       0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Sho (Solo) (CharaSelect)",       19154912,  PersonaNodes_CSel, Persona4PalettesSoloCSEL,   0xEB3630 },
    { L"char\\char_nb_pal.pac",    L"Sho Minazuki",                   278560,    PersonaNodes_Normal, Persona4PalettesSho,        0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Sho Minazuki (CharaSelect)",     19154912,  PersonaNodes_CSel, Persona4PalettesShoCSEL,    0xDF51D0 },
    { L"char\\char_ku_pal.pac",    L"Teddie/Kuma",                    278560,    PersonaNodes_Normal, Persona4PalettesTeddie,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Teddie/Kuma (CharaSelect)",      19154912,  PersonaNodes_CSel, Persona4PalettesTeddieCSEL, 0x7E18E0 },
    { L"char\\char_ad_pal.pac",    L"Tohru Adachi",                   278560,    PersonaNodes_Normal, Persona4PalettesTohru,      0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Tohru Adachi (CharaSelect)",     19154912,  PersonaNodes_CSel, Persona4PalettesTohruCSEL,  0xA0840  },
    { L"char\\char_yo_pal.pac",    L"Yosuke Hanamura",                278560,    PersonaNodes_Normal, Persona4PalettesYosuke,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Yosuke Hanamura (CharaSelect)",  19154912,  PersonaNodes_CSel, Persona4PalettesYosukeCSEL, 0x112DB70 },
    { L"char\\char_bc_pal.pac",    L"Yu Narukami",                    278560,    PersonaNodes_Normal, Persona4PalettesYu,         0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Yu Narukami (CharaSelect)",      19154912,  PersonaNodes_CSel, Persona4PalettesYuCSEL,     0x38EC60 },
    { L"char\\char_yk_pal.pac",    L"Yukari Takeba",                  278560,    PersonaNodes_Normal, Persona4PalettesYukari,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Yukari Takeba (CharaSelect)",    19154912,  PersonaNodes_CSel, Persona4PalettesYukariCSEL, 0x10BCCD0 },
    { L"char\\char_yu_pal.pac",    L"Yukiko Amagi",                   278560,    PersonaNodes_Normal, Persona4PalettesYukiko,     0x2040 },
    { L"ETC\\CHSLDotV.pac",        L"Yukiko Amagi (CharaSelect)",     19154912,  PersonaNodes_CSel, Persona4PalettesYukikoCSEL, 0x1234000 },

    //Unknown, doesnt follow the same format as other characters
    //{ L"char_e0_pal.pac",    L"Unknown?",           13280,     Persona4Names,    ARRAYSIZE(Persona4Names), 0x280,  0x0 },
};
