#pragma once

// To add characters or palette lists:
// * If you need a new character, add them to UMK3_SNES_UNITS.
// * Add an associated collection of their respective nodes
// * or expand nodes as needed
// * Then create the set of palettes for that character
// That should be it.  Good luck.

const std::vector<UINT16> UMK3_SNES_IMGIDS_USED =
{
    // Just stub this until we get sprites
    indexMK1Sprites_Goro,                // 0xAA
};

const sGame_PaletteDataset UMK3_SNES_CYRAX_PALETTES_P1[] =
{
    { L"Cyrax P1", 0x3EAD0F, 0x3EAD2F },
};

const sGame_PaletteDataset UMK3_SNES_CYRAX_PALETTES_P2[] =
{
    { L"Cyrax P2", 0x3EAD2F, 0x3EAD4F },
};

const sGame_PaletteDataset UMK3_SNES_ERMAC_PALETTES_P1[] =
{
    { L"Ermac P1", 0x3EAF2F, 0x3EAF4F },
};

const sGame_PaletteDataset UMK3_SNES_ERMAC_PALETTES_P2[] =
{
    { L"Ermac P2", 0x8C44D, 0x8C46D },
};

const sGame_PaletteDataset UMK3_SNES_JADE_PALETTES_P1[] =
{
    { L"Jade P1", 0x3ED46D, 0x3ED48D },
};

const sGame_PaletteDataset UMK3_SNES_JADE_PALETTES_P2[] =
{
    { L"Jade P2", 0x3ED4CD, 0x3ED4ED },
};

const sGame_PaletteDataset UMK3_SNES_JAX_PALETTES_P1[] =
{
    { L"Jax P1", 0x3FB8D0, 0x3FB8F0 },
};

const sGame_PaletteDataset UMK3_SNES_JAX_PALETTES_P2[] =
{
    { L"Jax P2", 0x3FB8F0, 0x3FB910 },
};

const sGame_PaletteDataset UMK3_SNES_KABAL_PALETTES_P1[] =
{
    { L"Kabal P1", 0x3FA21B, 0x3FA23B },
};

const sGame_PaletteDataset UMK3_SNES_KABAL_PALETTES_P2[] =
{
    { L"Kabal P2", 0x3FA23B, 0x3FA25B },
};

const sGame_PaletteDataset UMK3_SNES_KANO_PALETTES_P1[] =
{
    { L"Kano P1", 0xBFF20, 0xBFF40 },
};

const sGame_PaletteDataset UMK3_SNES_KANO_PALETTES_P2[] =
{
    { L"Kano P2", 0xBFF00, 0xBFF20 },
};

const sGame_PaletteDataset UMK3_SNES_KUNGLAO_PALETTES_P1[] =
{
    { L"Kung Lao P1", 0x3F9290, 0x3F92B0 },
};

const sGame_PaletteDataset UMK3_SNES_KUNGLAO_PALETTES_P2[] =
{
    { L"Kung Lao P2", 0x3F92B0, 0x3F92D0 },
};

const sGame_PaletteDataset UMK3_SNES_LIUKANG_PALETTES_P1[] =
{
    { L"Liu Kang P1", 0x3FA2DB, 0x3FA2FB },
};

const sGame_PaletteDataset UMK3_SNES_LIUKANG_PALETTES_P2[] =
{
    { L"Liu Kang P2", 0x3FA2FB, 0x3FA31B },
};

const sGame_PaletteDataset UMK3_SNES_MILEENA_PALETTES_P1[] =
{
    { L"Mileena P1", 0x3ED44B, 0x3ED46B },
};

const sGame_PaletteDataset UMK3_SNES_MILEENA_PALETTES_P2[] =
{
    { L"Mileena P2", 0x3ED4Ab, 0x3ED4Cb },
};

const sGame_PaletteDataset UMK3_SNES_NIGHTWOLF_PALETTES_P1[] =
{
    { L"Nightwolf P1", 0x3FB650, 0x3FB670 },
};

const sGame_PaletteDataset UMK3_SNES_NIGHTWOLF_PALETTES_P2[] =
{
    { L"Nightwolf P2", 0x3FB670, 0x3FB690 },
};

// Noob P1...?

const sGame_PaletteDataset UMK3_SNES_NOOB_PALETTES_P2[] =
{
    { L"Noob Saibot P2", 0x8C4ED, 0x8C50D },
};

const sGame_PaletteDataset UMK3_SNES_RAIN_PALETTES_P1[] =
{
    { L"Rain P1", 0x3EAFAF, 0x3EAFCF },
};

const sGame_PaletteDataset UMK3_SNES_RAIN_PALETTES_P2[] =
{
    { L"Rain P2", 0x8C4AD, 0x8C4CD },
};

const sGame_PaletteDataset UMK3_SNES_REPTILE_PALETTES_P1[] =
{
    { L"Reptile P1", 0x3EAFCF, 0x3EAFEF },
    { L"Reptile P1 FX", 0x3EAFEF, 0x3EB00F },
};

const sGame_PaletteDataset UMK3_SNES_REPTILE_PALETTES_P2[] =
{
    { L"Reptile P2", 0x8C4CD, 0x8C4ED },
};

const sGame_PaletteDataset UMK3_SNES_SCORPION_PALETTES_P1[] =
{
    { L"Scorpion P1", 0x3EAF0F, 0x3EAF2F },
};

const sGame_PaletteDataset UMK3_SNES_SCORPION_PALETTES_P2[] =
{
    { L"Scorpion P2", 0x8C42d, 0x8C44d },
};

const sGame_PaletteDataset UMK3_SNES_SEKTOR_PALETTES_P1[] =
{
    { L"Sektor P1", 0x3EACCF, 0x3EACEF },
};

const sGame_PaletteDataset UMK3_SNES_SEKTOR_PALETTES_P2[] =
{
    { L"Sektor P2", 0x3EACEF, 0x3EAD0F },
};

const sGame_PaletteDataset UMK3_SNES_SHANG_PALETTES_P1[] =
{
    { L"Shang Tsung P1", 0xDFF00, 0xDFF20 },
};

const sGame_PaletteDataset UMK3_SNES_SHANG_PALETTES_P2[] =
{
    { L"Shang Tsung P2", 0xDFF20, 0xDFF40 },
};

const sGame_PaletteDataset UMK3_SNES_SINDEL_PALETTES_P1[] =
{
    { L"Sindel P1", 0x15FF00, 0x15FF20 },
};

const sGame_PaletteDataset UMK3_SNES_SINDEL_PALETTES_P2[] =
{
    { L"Sindel P2", 0x15FF20, 0x15FF40 },
};

const sGame_PaletteDataset UMK3_SNES_SMOKE_PALETTES_P1[] =
{
    { L"Smoke P1", 0x3EAD6F, 0x3EAD8F },
};

const sGame_PaletteDataset UMK3_SNES_SMOKE_PALETTES_P2[] =
{
    { L"Smoke P2", 0x3EAD8F, 0x3EADAF },
};

const sGame_PaletteDataset UMK3_SNES_SMOKE_HUMAN_PALETTES_P1[] =
{
    { L"Smoke (Human) P1", 0x3EAF6F, 0x3EAF8F },
};

const sGame_PaletteDataset UMK3_SNES_SMOKE_HUMAN_PALETTES_P2[] =
{
    { L"Smoke (Human) P2", 0x8C48D, 0x8C4AD },
};

const sGame_PaletteDataset UMK3_SNES_SONYA_PALETTES_P1[] =
{
    { L"Sonya P1", 0xCFF00, 0xCFF20 },
};

const sGame_PaletteDataset UMK3_SNES_SONYA_PALETTES_P2[] =
{
    { L"Sonya P2", 0xCFF20, 0xCFF40 },
};

const sGame_PaletteDataset UMK3_SNES_STRYKER_PALETTES_P1[] =
{
    { L"Stryker P1", 0xAFF00, 0xAFF20 },
};

const sGame_PaletteDataset UMK3_SNES_STRYKER_PALETTES_P2[] =
{
    { L"Stryker P2", 0xAFF20, 0xAFF40 },
};

const sGame_PaletteDataset UMK3_SNES_SUBZERO_PALETTES_P1[] =
{
    { L"Sub-Zero P1", 0x3F91B0, 0x3F91D0 },
};

const sGame_PaletteDataset UMK3_SNES_SUBZERO_PALETTES_P2[] =
{
    { L"Sub-Zero P2", 0x3F91D0, 0x3F91F0 },
};

const sGame_PaletteDataset UMK3_SNES_SUBZERO_HUMAN_PALETTES_P1[] =
{
    { L"Sub-Zero (Original) P1", 0x3EAF4F, 0x3EAF6F },
};

const sGame_PaletteDataset UMK3_SNES_SUBZERO_HUMAN_PALETTES_P2[] =
{
    { L"Sub-Zero (Original) P2", 0x8C46D, 0x8C48D },
};

const sDescTreeNode UMK3_SNES_CYRAX_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_CYRAX_PALETTES_P1, ARRAYSIZE(UMK3_SNES_CYRAX_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_CYRAX_PALETTES_P2, ARRAYSIZE(UMK3_SNES_CYRAX_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_ERMAC_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_ERMAC_PALETTES_P1, ARRAYSIZE(UMK3_SNES_ERMAC_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_ERMAC_PALETTES_P2, ARRAYSIZE(UMK3_SNES_ERMAC_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_JADE_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JADE_PALETTES_P1, ARRAYSIZE(UMK3_SNES_JADE_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JADE_PALETTES_P2, ARRAYSIZE(UMK3_SNES_JADE_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_JAX_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JAX_PALETTES_P1, ARRAYSIZE(UMK3_SNES_JAX_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JAX_PALETTES_P2, ARRAYSIZE(UMK3_SNES_JAX_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_KABAL_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KABAL_PALETTES_P1, ARRAYSIZE(UMK3_SNES_KABAL_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KABAL_PALETTES_P2, ARRAYSIZE(UMK3_SNES_KABAL_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_KANO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KANO_PALETTES_P1, ARRAYSIZE(UMK3_SNES_KANO_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KANO_PALETTES_P2, ARRAYSIZE(UMK3_SNES_KANO_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_KUNGLAO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KUNGLAO_PALETTES_P1, ARRAYSIZE(UMK3_SNES_KUNGLAO_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KUNGLAO_PALETTES_P2, ARRAYSIZE(UMK3_SNES_KUNGLAO_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_LIUKANG_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_LIUKANG_PALETTES_P1, ARRAYSIZE(UMK3_SNES_LIUKANG_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_LIUKANG_PALETTES_P2, ARRAYSIZE(UMK3_SNES_LIUKANG_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_MILEENA_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_MILEENA_PALETTES_P1, ARRAYSIZE(UMK3_SNES_MILEENA_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_MILEENA_PALETTES_P2, ARRAYSIZE(UMK3_SNES_MILEENA_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_NIGHTWOLF_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NIGHTWOLF_PALETTES_P1, ARRAYSIZE(UMK3_SNES_NIGHTWOLF_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NIGHTWOLF_PALETTES_P2, ARRAYSIZE(UMK3_SNES_NIGHTWOLF_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_NOOB_COLLECTION[] =
{
    //{ L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NOOB_PALETTES_P1, ARRAYSIZE(UMK3_SNES_NOOB_PALETTES_P1) },
    { L"P2_", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NOOB_PALETTES_P2, ARRAYSIZE(UMK3_SNES_NOOB_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_RAIN_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_RAIN_PALETTES_P1, ARRAYSIZE(UMK3_SNES_RAIN_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_RAIN_PALETTES_P2, ARRAYSIZE(UMK3_SNES_RAIN_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_REPTILE_COLLECTION[] =
{
    // These are unequal, so opt out of pairing via affixing _
    { L"P1_", DESC_NODETYPE_TREE, (void*)UMK3_SNES_REPTILE_PALETTES_P1, ARRAYSIZE(UMK3_SNES_REPTILE_PALETTES_P1) },
    { L"P2_", DESC_NODETYPE_TREE, (void*)UMK3_SNES_REPTILE_PALETTES_P2, ARRAYSIZE(UMK3_SNES_REPTILE_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SCORPION_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SCORPION_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SCORPION_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SCORPION_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SCORPION_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SEKTOR_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SEKTOR_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SEKTOR_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SEKTOR_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SEKTOR_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SHANG_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SHANG_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SHANG_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SHANG_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SHANG_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SINDEL_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SINDEL_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SINDEL_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SINDEL_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SINDEL_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SMOKE_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SMOKE_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SMOKE_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SMOKE_HUMAN_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_HUMAN_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SMOKE_HUMAN_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_HUMAN_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SMOKE_HUMAN_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SONYA_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SONYA_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SONYA_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SONYA_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SONYA_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_STRYKER_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_STRYKER_PALETTES_P1, ARRAYSIZE(UMK3_SNES_STRYKER_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_STRYKER_PALETTES_P2, ARRAYSIZE(UMK3_SNES_STRYKER_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SUBZERO_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SUBZERO_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SUBZERO_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_SUBZERO_HUMAN_COLLECTION[] =
{
    { L"P1", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_HUMAN_PALETTES_P1, ARRAYSIZE(UMK3_SNES_SUBZERO_HUMAN_PALETTES_P1) },
    { L"P2", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_HUMAN_PALETTES_P2, ARRAYSIZE(UMK3_SNES_SUBZERO_HUMAN_PALETTES_P2) },
};

const sDescTreeNode UMK3_SNES_UNITS[] =
{
    { L"Cyrax", DESC_NODETYPE_TREE, (void*)UMK3_SNES_CYRAX_COLLECTION, ARRAYSIZE(UMK3_SNES_CYRAX_COLLECTION) },
    { L"Ermac", DESC_NODETYPE_TREE, (void*)UMK3_SNES_ERMAC_COLLECTION, ARRAYSIZE(UMK3_SNES_ERMAC_COLLECTION) },
    { L"Jade", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JADE_COLLECTION, ARRAYSIZE(UMK3_SNES_JADE_COLLECTION) },
    { L"Jax", DESC_NODETYPE_TREE, (void*)UMK3_SNES_JAX_COLLECTION, ARRAYSIZE(UMK3_SNES_JAX_COLLECTION) },
    { L"Kabal", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KABAL_COLLECTION, ARRAYSIZE(UMK3_SNES_KABAL_COLLECTION) },
    { L"Kano", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KANO_COLLECTION, ARRAYSIZE(UMK3_SNES_KANO_COLLECTION) },
    { L"Kung Lao", DESC_NODETYPE_TREE, (void*)UMK3_SNES_KUNGLAO_COLLECTION, ARRAYSIZE(UMK3_SNES_KUNGLAO_COLLECTION) },
    { L"Liu Kang", DESC_NODETYPE_TREE, (void*)UMK3_SNES_LIUKANG_COLLECTION, ARRAYSIZE(UMK3_SNES_LIUKANG_COLLECTION) },
    { L"Mileena", DESC_NODETYPE_TREE, (void*)UMK3_SNES_MILEENA_COLLECTION, ARRAYSIZE(UMK3_SNES_MILEENA_COLLECTION) },
    { L"Nightwolf", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NIGHTWOLF_COLLECTION, ARRAYSIZE(UMK3_SNES_NIGHTWOLF_COLLECTION) },
    { L"Noob Saibot", DESC_NODETYPE_TREE, (void*)UMK3_SNES_NOOB_COLLECTION, ARRAYSIZE(UMK3_SNES_NOOB_COLLECTION) },
    { L"Rain", DESC_NODETYPE_TREE, (void*)UMK3_SNES_RAIN_COLLECTION, ARRAYSIZE(UMK3_SNES_RAIN_COLLECTION) },
    { L"Reptile", DESC_NODETYPE_TREE, (void*)UMK3_SNES_REPTILE_COLLECTION, ARRAYSIZE(UMK3_SNES_REPTILE_COLLECTION) },
    { L"Scorpion", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SCORPION_COLLECTION, ARRAYSIZE(UMK3_SNES_SCORPION_COLLECTION) },
    { L"Sektor", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SEKTOR_COLLECTION, ARRAYSIZE(UMK3_SNES_SEKTOR_COLLECTION) },
    { L"Shang Tsung", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SHANG_COLLECTION, ARRAYSIZE(UMK3_SNES_SHANG_COLLECTION) },
    { L"Sindel", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SINDEL_COLLECTION, ARRAYSIZE(UMK3_SNES_SINDEL_COLLECTION) },
    { L"Smoke", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_COLLECTION, ARRAYSIZE(UMK3_SNES_SMOKE_COLLECTION) },
    { L"Smoke (Human)", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SMOKE_HUMAN_COLLECTION, ARRAYSIZE(UMK3_SNES_SMOKE_HUMAN_COLLECTION) },
    { L"Sonya", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SONYA_COLLECTION, ARRAYSIZE(UMK3_SNES_SONYA_COLLECTION) },
    { L"Stryker", DESC_NODETYPE_TREE, (void*)UMK3_SNES_STRYKER_COLLECTION, ARRAYSIZE(UMK3_SNES_STRYKER_COLLECTION) },
    { L"Sub-Zero", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_COLLECTION, ARRAYSIZE(UMK3_SNES_SUBZERO_COLLECTION) },
    { L"Sub-Zero (Human)", DESC_NODETYPE_TREE, (void*)UMK3_SNES_SUBZERO_HUMAN_COLLECTION, ARRAYSIZE(UMK3_SNES_SUBZERO_HUMAN_COLLECTION) },
};

constexpr auto UMK3_SNES_NUMUNIT = ARRAYSIZE(UMK3_SNES_UNITS);

constexpr auto UMK3_SNES_EXTRALOC = UMK3_SNES_NUMUNIT;

// We extend this array with data groveled from the extensible extras file, if any.
const stExtraDef UMK3_SNES_EXTRA[] =
{
    // Start
    { UNIT_START_VALUE },

    { INVALID_UNIT_VALUE }
};
